name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Container
        run: bash build.sh
      - name: Push Container
        if: ${{ github.event_name != 'pull_request' }}
        run: bash push.sh
